class AddFurtherQuestionsToUsers < ActiveRecord::Migration[5.0]
  def change
    add_column :users, :Q1_1, :integer
    add_column :users, :Q1_2, :integer
    add_column :users, :Q1_3, :integer
    add_column :users, :Q1_4, :integer
    add_column :users, :Q2_1, :integer
    add_column :users, :Q2_2, :integer
    add_column :users, :Q2_3, :integer
    add_column :users, :Q2_4, :integer
    add_column :users, :Q3_1, :integer
    add_column :users, :Q3_2, :integer
    add_column :users, :Q3_3, :integer
    add_column :users, :Q3_4, :integer
    add_column :users, :Q4_1, :integer
    add_column :users, :Q4_2, :integer
    add_column :users, :Q4_3, :integer
    add_column :users, :Q4_4, :integer
    add_column :users, :Q5_1, :integer
    add_column :users, :Q5_2, :integer
    add_column :users, :Q5_3, :integer
    add_column :users, :Q5_4, :integer
    add_column :users, :Q6_1, :integer
    add_column :users, :Q6_2, :integer
    add_column :users, :Q6_3, :integer
    add_column :users, :Q6_4, :integer
    add_column :users, :Q7_1, :integer
    add_column :users, :Q7_2, :integer
    add_column :users, :Q7_3, :integer
    add_column :users, :Q7_4, :integer
    add_column :users, :Q8_1, :integer
    add_column :users, :Q8_2, :integer
    add_column :users, :Q8_3, :integer
    add_column :users, :Q8_4, :integer
    add_column :users, :Q9_1, :integer
    add_column :users, :Q9_2, :integer
    add_column :users, :Q9_3, :integer
    add_column :users, :Q9_4, :integer
    add_column :users, :Q10_1, :integer
    add_column :users, :Q10_2, :integer
    add_column :users, :Q10_3, :integer
    add_column :users, :Q10_4, :integer
    add_column :users, :Q11_1, :integer
    add_column :users, :Q11_2, :integer
    add_column :users, :Q11_3, :integer
    add_column :users, :Q11_4, :integer
    add_column :users, :Q12_1, :integer
    add_column :users, :Q12_2, :integer
    add_column :users, :Q12_3, :integer
    add_column :users, :Q12_4, :integer
    add_column :users, :Q13_1, :integer
    add_column :users, :Q13_2, :integer
    add_column :users, :Q13_3, :integer
    add_column :users, :Q13_4, :integer
    add_column :users, :Q14_1, :integer
    add_column :users, :Q14_2, :integer
    add_column :users, :Q14_3, :integer
    add_column :users, :Q14_4, :integer
    add_column :users, :Q15_1, :integer
    add_column :users, :Q15_2, :integer
    add_column :users, :Q15_3, :integer
    add_column :users, :Q15_4, :integer
    add_column :users, :Q16_1, :integer
    add_column :users, :Q16_2, :integer
    add_column :users, :Q16_3, :integer
    add_column :users, :Q16_4, :integer
    add_column :users, :Q17_1, :integer
    add_column :users, :Q17_2, :integer
    add_column :users, :Q17_3, :integer
    add_column :users, :Q17_4, :integer
    add_column :users, :Q18_1, :integer
    add_column :users, :Q18_2, :integer
    add_column :users, :Q18_3, :integer
    add_column :users, :Q18_4, :integer
  end
end
